#!/usr/bin/env bash

set -xeuf -o pipefail

trap 'trap - SIGTERM && kill -- -$$' SIGINT SIGTERM EXIT

rofi_error() {
    rofi -theme-str '* { background: var(red); }' -dmenu -p "$1"
}

# Check if service is running
service_is_running() {
    # curl health endpoint
    curl --silent --fail --show-error \
        "http://$$WASTE_ENDPOINT/openapi.json" && return 0 || return 1
}

# Request transcription
service_request() {
    curl --silent --fail --show-error \
        "http://$$WASTE_ENDPOINT/asr?encode=true&task=transcribe&language=$1&word_timestamps=false&output=json" \
        -H 'Content-Type: multipart/form-data' \
        -H 'accept: application/json' \
        -F "Content-Disposition=form-data" \
        -F "audio_file=@$2" \
        -F "Content-Type=audio/wav"
}

# retry 3 times before giving up
try_service_request() {
    for i in {1..3}; do
        result=$(service_request "$1" "$2" || echo "error")
        if [ "$result" != "error" ]; then
            echo "$result"
            return 0
        fi
        logger -s "Failed to get response, retrying ($i)"
        sleep 1
    done
    return 1
}

logger -s "Invoking whisper"

# Set the audio source
audio_source=$$AUDIO_DEVICE

# Check if audio source is muted
is_muted=$(pacmd list-sources | grep -A 11 "$audio_source" | awk '/muted/ {print $2; exit}')

# If muted print error and exit
if [ "$is_muted" = "yes" ]; then
    rofi_error "Audio source is muted, unmute before speaking"
    exit 1
fi

# Check if audio source is busy
is_busy=$(pacmd list-sources | grep -A 6 "$audio_source" | awk '/state/ {print $2; exit}')

# If running or idle, print error and exit
if [ "$is_busy" = "RUNNING" ] || [ "$is_busy" = "IDLE" ]; then
    rofi_error "Audio source is busy ($is_busy), free it and try again"
    exit 1
fi

# Print error and exit if not active
if ! service_is_running; then

    if [ "$IS_REMOTE" = "false" ]; then
        rofi_error "Whisper was not running, starting service using systemctl"
        systemctl --user start waste.service
        exit 1
    fi

    rofi_error "Whisper is not running, check remote service"
    exit 1
fi

# Create a temporary file for the audio to be stored
temp_file16khz=$(mktemp -t "stt-XXXXXXXXXX.wav")

# Find the right microphone
device_string=$(pacmd list-sources | grep -A60 "$audio_source" | grep "device.string = \"" | head -n1 | cut -d'"' -f2)

# Find the number of channels
device_channels=$(pacmd list-sources | grep -A20 "$audio_source" | grep "channel map:" | cut -d':' -f2- | tr ',' '\n' | wc -l)

PID_FILE="/tmp/rofi-waste-request.pid"

# Record audio from the microphone and save it to the temporary file
arecord --device="$device_string" -f S16_LE -c "$device_channels" -r 16000 --process-id-file "$PID_FILE" "$temp_file16khz" &

# Set language options
language_options=$(echo "$$LANGS" | tr ',' '\n')

# Select language using rofi
lang=$( (echo -e "$language_options";)  | rofi -dmenu -p "Speak now" || true)

logger -s "Selected language: \"$lang\""

# Stop the recording process
kill "$(cat $PID_FILE)"

# If language is empty exit
if [ -z "$lang" ]; then
    logger -s "No language selected"
    exit 0
fi

# untrap after killing the recording process
trap - SIGINT SIGTERM EXIT

output=$(try_service_request "$lang" "$temp_file16khz" | jq '.text' -r | sed "s/^\ //" | sed -E -f "$$PATTERNS_FILE")

logger -s "$output"

echo -n "$output" | xclip -selection clipboard

dunstify -h "string:bgcolor:#4444FF" "$output" ""
